Added the plot method
QMCSoftware/QMCSoftware pull request #308
Opened 2023-01-05 03:45 UTC by Baronlegend27

I made the abstract method called plot. I am pretty sure everything is correct, however I wrote a lot of documentation for the method.

2023-01-05 18:54 UTC, Baronlegend27 reviewed
I made the abstract method called plot. I am pretty sure everything is correct, however I wrote a lot of documentation for the method.

2023-01-06 15:26 UTC, alegresor requested changes
@Baronlegend27 This is a good start, the documentation for the method looks nice, I left some suggestions in this review. You still need to implement the method. This is not an abstract method but rather a method in the abstract class. Any subclass will inherit this `plot` method so you do not need to rewrite this method for every discrete distribution.

2023-01-06 15:26 UTC, alegresor commented on qmcpy/discrete_distribution/_discrete_distribution.py
> +        ABSTRACT METHOD for ploting a distrubution, you will also need to import matplotlib.pyplot as plt
Although this method is in the abstract class, this is not an abstract method. 

You should `impot matplotlib.pyplot as plt` in the routine. If you put this import in a try-except then you can throw a friendly error for the user who tries to call this routine without having matplotlib installed.

2023-01-06 15:26 UTC, alegresor commented on qmcpy/discrete_distribution/_discrete_distribution.py
> +            n (int): n is the number of samples that will be calculated
maybe "plotted" instead of "calculated"

2023-01-06 15:26 UTC, alegresor commented on qmcpy/discrete_distribution/_discrete_distribution.py
> +
we don't leave white space between arguments

2023-01-06 15:26 UTC, alegresor commented on qmcpy/discrete_distribution/_discrete_distribution.py
> +            d_vertical (int): d_vertical is the index of points that will be plotted on the vertical axis. See below
you don't need the "see below"

2023-01-06 15:26 UTC, alegresor commented on qmcpy/discrete_distribution/_discrete_distribution.py
> +            x-axis and the d_vertical index will then become the y-axis.
you probably don't need this. I think the the strings for `d_vertical` and `d_horizontal` are sufficient. please fix the spelling of horizontal.

2023-01-06 15:26 UTC, alegresor commented on qmcpy/discrete_distribution/_discrete_distribution.py
> +            plt.show()
Move this into the method so it executes when called

2023-01-06 15:26 UTC, alegresor commented on qmcpy/discrete_distribution/_discrete_distribution.py
> +        This method does not return anything it just plots a scatter plot.
return the `fig,ax` in case the user wants to further modify our baseline plots.

2023-01-06 15:26 UTC, alegresor commented on qmcpy/discrete_distribution/_discrete_distribution.py
> +        raise MethodImplementationError(self, 'plot')
the code for plotting that you currently have in the docstring goes here

2023-01-15 15:28 UTC, alegresor requested changes
Looks better! Left a few more suggestions on how to improve the method. 

You may also allow a user to pass in an `ax` argument which defaults to `None`. If an `ax` is passed in, you may just use that one to make the scatter plot on. If `ax is None` then you can create the `fig,ax` for the user. 

Add some commands to pretty up the plot e.g. ones that set the aspect ratio, axis labels, axis ticks, axis limits

2023-01-15 15:28 UTC, alegresor commented on qmcpy/discrete_distribution/_discrete_distribution.py
> +import matplotlib.pyplot as plt
Move this into a try except within the method

2023-01-15 15:28 UTC, alegresor commented on qmcpy/discrete_distribution/_discrete_distribution.py
> +        try:
the try except should only try to `import matplotlib.pyplot as plt` and except an error that it is not installed.

2023-01-15 15:28 UTC, alegresor commented on qmcpy/discrete_distribution/_discrete_distribution.py
>              fig, ax = plt.subplots(nrows=1, ncols=1, figsize=(16, 6))
figsize=(16,6) will be quite wide for a 1 column by 1 row plot. Maybe try something like (5,5) or play around with these values

2023-01-15 15:28 UTC, alegresor commented on qmcpy/discrete_distribution/_discrete_distribution.py
>              ax.scatter(samples[:, d_vertical], samples[:, d_horizontial])
switch d_vertical and d_horizontal. The first argument is the x axis locations (horizontal) and the second argument is the y axis locations (vertical)

2023-01-15 15:28 UTC, alegresor commented on qmcpy/discrete_distribution/_discrete_distribution.py
>              plt.show()
don't show the plot, just return the fig,ax (as you have)

2023-03-13 15:59 UTC, alegresor approved these changes

2023-03-13 15:59 UTC, merged